channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=25.0
  - python=3.10.0
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.4.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - bitsandbytes==0.45.3
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - datasets==3.3.2
      - deepspeed==0.16.5
      - dill==0.3.8
      - einops==0.8.1
      - filelock==3.17.0
      - flash-attn==2.5.8
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - hjson==3.1.0
      - huggingface-hub==0.29.2
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.14.0
      - portalocker==3.1.1
      - propcache==0.3.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tokenizers==0.21.1
      - torch==2.3.1
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==2.3.1
      - trl==0.15.2
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
